### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Angell1993** [RareDevs/Rare#112]
**Describe the bug**
I wanted to try out the new version of Rare, But it doesn't seem to work for some reason..

[angel@angel-openbox Downloads]$ ./Rare.AppImage
Traceback (most recent call last):
  File "/tmp/.mount_Rare.AHSEzcB//usr/src/__main__.py", line 84, in <module>
    main()
  File "/tmp/.mount_Rare.AHSEzcB//usr/src/__main__.py", line 79, in main
    from rare.app import start
  File "/tmp/.mount_Rare.AHSEzcB/usr/src/rare/app.py", line 13, in <module>
    from legendary.core import LegendaryCore
ModuleNotFoundError: No module named 'legendary.core'

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Manjaro 21.1.5 Pahvo
 - Version 1.7.b1
- Installation AppImage
- Python version Lastest

**Comment by Dummerle** [comment]
Thanks for reporting!

I fixed the bug. You can download AppImage here: https://github.com/Dummerle/Rare/actions/runs/1326557608

**Comment by Angell1993** [comment]
Unless you can provide a new appimage, with the changes you made, it still present, even if I download from your link above..

**Comment by loathingKernel** [comment]
Please note that Issues is not a discussion board. We are interested in your comments, please join us on Discord if you like, or keep it in a single comment.
