### ISSUE TITLE
[BUG] Unable to launch any games

### ISSUE THREAD

**Issue by y2k04** [RareDevs/Rare#339]
**Describe the bug**
Rare is unable to launch any games. It can install them no problem, just cannot launch the process.

**To Reproduce**

1. Open Rare
2. Click Launch on any game
3. See error

**Screenshots**

![image](https://github.com/RareDevs/Rare/assets/29883287/406750c1-5fab-42fd-8e30-df6b8f98f9a9)

**System information**

Please complete the following information
- Operating system: Windows 11 23H2
- Rare Version: 1.10.7
- Installation method: pip (VirtualEnv)
- Python version: 3.11.2

**Log displaying error**
```
[Rare] INFO: Launching Rare version 1.10.7
[Rare] INFO: Operating System: Windows
[LGDLFS] INFO: Using Rare's LGDLFS monkey
[Core] INFO: Using Rare's LegendaryCore monkey
[Core] INFO: Logging in...
[LaunchDialog] INFO: You are logged in
[RareCore] INFO: Got API results for COMBINED
[LaunchDialog] INFO: App starting
[Rare] INFO: Renewed session expires at 2023-12-17T10:49:49.150Z
[MainWindow] WARNING: Discord RPC module not found
[WineResolver] INFO: Origin game Star Wars Squadrons is not installed
[WineResolver] INFO: Origin worker finished in 0.017055273056030273s
[RareGame] INFO: Start new Process: (E:\Games\Legendary\Scripts\pythonw.exe E:\Games\Legendary\scripts\rare launch Fortnite)
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
```

**Comment by loathingKernel** [comment]
Use one of the packages and do not install it through pip. Why did you select that method though? Is is convenient somehow? I am thinking of removing it from Readme completely.

**Comment by loathingKernel** [comment]
It tested the `pip` method on Linux with the upcoming release and it worked. It should also work on Windows in the new version. I will leave this issue open until you can verify that it works for you too.

**Comment by y2k04** [comment]
> Please verify if it is happening using one of the packages or try it with pip and the development version directly from git. The underlying issue should be fixed in the development version.
> 
> Why did you select that method though? Is is convenient somehow? I am asking beacuse I am thinking of removing it from Readme.

I had downloaded the main repo and ran `pip -e .`

**Comment by y2k04** [comment]
Okay so, 1.10.6 (pip latest release) works fine. The version that was causing me problems was 1.10.7. I do notice that there is an update for Rare for 1.10.9, but that is not on pip yet.

**Comment by y2k04** [comment]
Ok, I tested 1.10.9 and it is as broken as 1.10.7. Same issue is occurring.

```
[Rare] INFO: Launching Rare version 1.10.9
[Rare] INFO: Operating System: Windows
[LGDLFS] INFO: Using Rare's LGDLFS monkey
[Core] INFO: Using Rare's LegendaryCore monkey
[Core] INFO: Using config in C:\Users\<username>/.config/legendary
[Core] INFO: Trying to re-use existing login session...
[LaunchDialog] INFO: You are logged in
[FetchWorker] INFO: Requesting Windows metadata, without Unreal engine
[RareCore] INFO: Got API results for COMBINED
[LaunchDialog] INFO: App starting
[Rare] INFO: Renewed session expires at 2023-12-18T09:49:13.903Z
[MainWindow] WARNING: Discord RPC module not found
[WineResolver] INFO: Origin game Star Wars Squadrons is not installed
[WineResolver] INFO: Origin worker finished in 0.0s
[RareGame] INFO: Start new Process: (E:\Games\Legendary\Scripts\pythonw.exe E:\Games\Legendary\scripts\rare launch Fortnite)
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name
[GameProcess] ERROR: Fortnite (Fortnite): QLocalSocket::connectToServer: Invalid name

```

**Comment by y2k04** [comment]
I do notice something peculiar however: `[Core] INFO: Using config in C:\Users\<username>/.config/legendary`
I did not hide my username, that is how it is displayed in the log... 🤔

**Comment by loathingKernel** [comment]
The name hiding is my doing. I was considering anonymizing the logs but that's most likely in vain.

**Comment by loathingKernel** [comment]
The problem was related to the change from `consoles_script` to `gui_script` in `setup.py`. And it was only relevant on Windows. The commit above should fix it.

You could easily install with `pip install https://github.com/RareDevs/Rare/archive/c068b1f1830ce4e1494abf1d1912b8499634a33f.zip`

PyPI will be updated soon too.

**Comment by y2k04** [comment]
It works, thank you! Rare still doesn't have a terminal output, but at least games launch now.
